"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

export default function ProfilePage(){
  const [form,setForm]=useState<any>({displayName:"",username:"",bio:"",preferredUiLanguage:"en",dialect:"",region:"",district:"",village:"",audioConsent:false,researchConsent:false,modelTrainingConsent:false,datasetLicense:""}); const [message,setMessage]=useState("");
  useEffect(()=>{fetch("/api/profile").then(async r=>{if(r.status===401){window.location.href="/login";return}const d=await r.json();setForm({...form,...d.user, ...(d.user.profile||{})});})},[]);
  async function submit(e:FormEvent){e.preventDefault();const r=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();setMessage(r.ok?"Profile saved.":d.error||"Unable to save.");if(r.ok)setForm({...form,...d.user,...(d.user.profile||{})});}
  return <main className="pageShell"><div className="sectionLabel">PROFILE</div><div className="formHeader"><div><h1>Your contributor profile.</h1><p>Share useful linguistic context without requiring an exact address.</p></div><Link href="/dashboard">Dashboard</Link></div><form className="contributionForm" onSubmit={submit}><div className="twoCol"><label>Display name<input value={form.displayName||""} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>Username<input value={form.username||""} onChange={e=>setForm({...form,username:e.target.value})}/></label></div><label>Bio<textarea rows={4} value={form.bio||""} onChange={e=>setForm({...form,bio:e.target.value})}/></label><div className="twoCol"><label>Dialect<input value={form.dialect||""} onChange={e=>setForm({...form,dialect:e.target.value})}/></label><label>Region<input value={form.region||""} onChange={e=>setForm({...form,region:e.target.value})}/></label><label>District<input value={form.district||""} onChange={e=>setForm({...form,district:e.target.value})}/></label><label>Village <span>(optional)</span><input value={form.village||""} onChange={e=>setForm({...form,village:e.target.value})}/></label></div><label>Preferred interface<select value={form.preferredUiLanguage||"en"} onChange={e=>setForm({...form,preferredUiLanguage:e.target.value})}><option value="en">English</option><option value="ur">Urdu</option><option value="khw">Khowar</option></select></label><div className="checks"><label><input type="checkbox" checked={!!form.audioConsent} onChange={e=>setForm({...form,audioConsent:e.target.checked})}/> I consent to my submitted audio being used according to the dataset license.</label><label><input type="checkbox" checked={!!form.researchConsent} onChange={e=>setForm({...form,researchConsent:e.target.checked})}/> I consent to research use.</label><label><input type="checkbox" checked={!!form.modelTrainingConsent} onChange={e=>setForm({...form,modelTrainingConsent:e.target.checked})}/> I consent to model-training use.</label></div>{message&&<div className="successBox">{message}</div>}<button className="button">Save profile</button></form></main>;
}
